/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CAPA_PRESENTACION;

import static java.awt.Frame.MAXIMIZED_BOTH;
/**
 *
 * @author Freak
 * @version Beta
 */
public class FRMMenuAdmin extends javax.swing.JFrame {
    /**
     * Creates new form FRMRegistrarEmpleado
     */
    // <editor-fold defaultstate="collapsed" desc="Construcotr">
    public FRMMenuAdmin() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        pNLEmpleados.setVisible(false);
        pNLDoctores.setVisible(false);
    }// </editor-fold>
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        txtLoginTitle = new javax.swing.JLabel();
        pnlBordeNegro = new javax.swing.JPanel();
        pNLEmpleados = new CAPA_PRESENTACION.ADMIN.PNLEmpleados();
        pNLDoctores = new CAPA_PRESENTACION.ADMIN.PNLDoctor();
        jmbAdmin = new javax.swing.JMenuBar();
        jmbRegistrar = new javax.swing.JMenu();
        jmiEmpleado = new javax.swing.JMenuItem();
        jmiDoctor = new javax.swing.JMenuItem();
        jmbReportes = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("frmRegistrarEmpleado"); // NOI18N

        txtLoginTitle.setFont(new java.awt.Font("Myriad CAD", 1, 24)); // NOI18N
        txtLoginTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtLoginTitle.setText(Glosario.Glosario.getAdministrador());
        txtLoginTitle.setToolTipText("");
        txtLoginTitle.setAlignmentX(100.0F);
        txtLoginTitle.setAlignmentY(100.0F);

        pnlBordeNegro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout pnlBordeNegroLayout = new javax.swing.GroupLayout(pnlBordeNegro);
        pnlBordeNegro.setLayout(pnlBordeNegroLayout);
        pnlBordeNegroLayout.setHorizontalGroup(
            pnlBordeNegroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pNLDoctores, javax.swing.GroupLayout.DEFAULT_SIZE, 1277, Short.MAX_VALUE)
            .addComponent(pNLEmpleados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlBordeNegroLayout.setVerticalGroup(
            pnlBordeNegroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBordeNegroLayout.createSequentialGroup()
                .addComponent(pNLEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pNLDoctores, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlBordeNegro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtLoginTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtLoginTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlBordeNegro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane2.setViewportView(jPanel2);

        jmbRegistrar.setText(Glosario.Glosario.getRegistrar());

        jmiEmpleado.setText("Empleado");
        jmiEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiEmpleadoActionPerformed(evt);
            }
        });
        jmbRegistrar.add(jmiEmpleado);

        jmiDoctor.setText("Doctor");
        jmiDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiDoctorActionPerformed(evt);
            }
        });
        jmbRegistrar.add(jmiDoctor);

        jmbAdmin.add(jmbRegistrar);

        jmbReportes.setText("REPORTES");
        jmbAdmin.add(jmbReportes);

        jMenu2.setText("CONFIGURACIONES");
        jmbAdmin.add(jMenu2);

        setJMenuBar(jmbAdmin);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // <editor-fold defaultstate="collapsed" desc="evento del MenuBar">
    private void jmiEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiEmpleadoActionPerformed
        // TODO add your handling code here:
        pNLEmpleados.setVisible(true);
        pNLDoctores.setVisible(false);
        pNLEmpleados.repaint();
    }//GEN-LAST:event_jmiEmpleadoActionPerformed

    private void jmiDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiDoctorActionPerformed
        // TODO add your handling code here:
        pNLDoctores.setVisible(true);
        pNLEmpleados.setVisible(false);
        pNLDoctores.repaint();
    }//GEN-LAST:event_jmiDoctorActionPerformed
    // </editor-fold>
    /**
     * @param args the command line arguments
     */
    // <editor-fold defaultstate="collapsed" desc="clase main">
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRMMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRMMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRMMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRMMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRMMenuAdmin().setVisible(true);
            }
        });
    }// </editor-fold>
    // <editor-fold defaultstate="collapsed" desc="Declaracion de variables">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuBar jmbAdmin;
    private javax.swing.JMenu jmbRegistrar;
    private javax.swing.JMenu jmbReportes;
    private javax.swing.JMenuItem jmiDoctor;
    private javax.swing.JMenuItem jmiEmpleado;
    private CAPA_PRESENTACION.ADMIN.PNLDoctor pNLDoctores;
    private CAPA_PRESENTACION.ADMIN.PNLEmpleados pNLEmpleados;
    private javax.swing.JPanel pnlBordeNegro;
    private javax.swing.JLabel txtLoginTitle;
    // End of variables declaration//GEN-END:variables
    // </editor-fold>
}
