/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CAPA_PRESENTACION;



/**
 *
 * @author Freak
 * @version Beta
 */
public class FRMMenuEmpleado extends javax.swing.JFrame {

    /**
     * Creates new form FRMMenuEmpleado
     * @param idEmpleado
     */
    // <editor-fold defaultstate="collapsed" desc="Construcotr">
    public FRMMenuEmpleado(int idEmpleado) {
        FRMMenuEmpleado.idEmpleado=idEmpleado;
        initComponents();
        pNLRegistrarProducto.setVisible(false);
        pNLSurtirProducto.setVisible(true);
        pNLBajaProducto.setVisible(false);
        setExtendedState(MAXIMIZED_BOTH);
    }
    // </editor-fold>
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        pNLRegistrarProducto1 = new CAPA_PRESENTACION.EMPLEADO.PNLRegistrarProducto();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        txtEmpleadoTitle = new javax.swing.JLabel();
        pnlBordeNegro = new javax.swing.JPanel();
        pNLRegistrarProducto = new CAPA_PRESENTACION.EMPLEADO.PNLRegistrarProducto();
        pNLSurtirProducto = new CAPA_PRESENTACION.EMPLEADO.PNLSurtirProducto();
        pNLBajaProducto = new CAPA_PRESENTACION.EMPLEADO.PNLBajaProducto();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jbmProducto = new javax.swing.JMenu();
        jmiProveer = new javax.swing.JMenuItem();
        jmiRegistrar = new javax.swing.JMenuItem();
        jmiBaja = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtEmpleadoTitle.setFont(new java.awt.Font("Myriad CAD", 1, 24)); // NOI18N
        txtEmpleadoTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtEmpleadoTitle.setText("EMPLEADO");
        txtEmpleadoTitle.setToolTipText("");
        txtEmpleadoTitle.setAlignmentX(100.0F);
        txtEmpleadoTitle.setAlignmentY(100.0F);

        pnlBordeNegro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout pnlBordeNegroLayout = new javax.swing.GroupLayout(pnlBordeNegro);
        pnlBordeNegro.setLayout(pnlBordeNegroLayout);
        pnlBordeNegroLayout.setHorizontalGroup(
            pnlBordeNegroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBordeNegroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBordeNegroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBordeNegroLayout.createSequentialGroup()
                        .addComponent(pNLRegistrarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(282, 282, 282))
                    .addGroup(pnlBordeNegroLayout.createSequentialGroup()
                        .addGroup(pnlBordeNegroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pNLBajaProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pNLSurtirProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pnlBordeNegroLayout.setVerticalGroup(
            pnlBordeNegroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBordeNegroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pNLRegistrarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pNLSurtirProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pNLBajaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEmpleadoTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 1123, Short.MAX_VALUE)
                    .addComponent(pnlBordeNegro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtEmpleadoTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlBordeNegro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel1);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jbmProducto.setText("PRODUCTO");

        jmiProveer.setText("SURTIR");
        jmiProveer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiProveerActionPerformed(evt);
            }
        });
        jbmProducto.add(jmiProveer);

        jmiRegistrar.setText("REGISTRAR");
        jmiRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRegistrarActionPerformed(evt);
            }
        });
        jbmProducto.add(jmiRegistrar);

        jmiBaja.setText("BAJA");
        jmiBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiBajaActionPerformed(evt);
            }
        });
        jbmProducto.add(jmiBaja);

        jMenuBar1.add(jbmProducto);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1135, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRegistrarActionPerformed
        // TODO add your handling code here:
        pNLRegistrarProducto.setVisible(true);
        pNLSurtirProducto.setVisible(false);
        pNLBajaProducto.setVisible(false);
    }//GEN-LAST:event_jmiRegistrarActionPerformed

    private void jmiProveerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiProveerActionPerformed
        // TODO add your handling code here:
        pNLRegistrarProducto.setVisible(false);
        pNLSurtirProducto.setVisible(true);
        pNLBajaProducto.setVisible(false);
    }//GEN-LAST:event_jmiProveerActionPerformed

    private void jmiBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiBajaActionPerformed
        // TODO add your handling code here:
        pNLRegistrarProducto.setVisible(false);
        pNLSurtirProducto.setVisible(false);
        pNLBajaProducto.setVisible(true);
    }//GEN-LAST:event_jmiBajaActionPerformed


    /**
     * @param args the command line arguments
     */
    // <editor-fold defaultstate="collapsed" desc="clase main">
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRMMenuEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRMMenuEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRMMenuEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRMMenuEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRMMenuEmpleado(idEmpleado).setVisible(true);
            }
        });
    }
    // </editor-fold>
    // <editor-fold defaultstate="collapsed" desc="Delaracion de variables">
    public static int idEmpleado;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu jbmProducto;
    private javax.swing.JMenuItem jmiBaja;
    private javax.swing.JMenuItem jmiProveer;
    private javax.swing.JMenuItem jmiRegistrar;
    private CAPA_PRESENTACION.EMPLEADO.PNLBajaProducto pNLBajaProducto;
    private CAPA_PRESENTACION.EMPLEADO.PNLRegistrarProducto pNLRegistrarProducto;
    private CAPA_PRESENTACION.EMPLEADO.PNLRegistrarProducto pNLRegistrarProducto1;
    private CAPA_PRESENTACION.EMPLEADO.PNLSurtirProducto pNLSurtirProducto;
    private javax.swing.JPanel pnlBordeNegro;
    private javax.swing.JLabel txtEmpleadoTitle;
    // End of variables declaration//GEN-END:variables
    // </editor-fold>
}
