/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CAPA_PRESENTACION.ADMIN;

import CAPA_NEGOCIOS.EMPLEADO;
import static CAPA_PRESENTACION.ADMIN.PNLTablaEmpleados.idEmpleado;
import CAPA_PRESENTACION.HILOS.TIPOS;
import javax.swing.JOptionPane;
/**
 *
 * @author Freak
 * @version Beta
 */
public class PNLRegistrarEmpleado extends javax.swing.JPanel {

    /**
     * Creates new form PNLRegistrar
     */
    // <editor-fold defaultstate="collapsed" desc="Constructor">
    public PNLRegistrarEmpleado() {
        initComponents();
    }// </editor-fold>
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtRegistrarEmpleado = new javax.swing.JLabel();
        pnlBordeNegro = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        lblAppPaterno = new javax.swing.JLabel();
        lblApmMaterno = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblContraseña = new javax.swing.JLabel();
        lblRepetirContraseña = new javax.swing.JLabel();
        txtnbEmpleado = new javax.swing.JTextField();
        txtappEmpleado = new javax.swing.JTextField();
        txtapmEmpleado = new javax.swing.JTextField();
        txtusuario = new javax.swing.JTextField();
        pwdEmpleado = new javax.swing.JPasswordField();
        pwdComparar = new javax.swing.JPasswordField();
        btnRegistrarE = new javax.swing.JButton();
        btnCancelarE = new javax.swing.JButton();

        txtRegistrarEmpleado.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtRegistrarEmpleado.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtRegistrarEmpleado.setText("Registar empleado");
        txtRegistrarEmpleado.setToolTipText("");
        txtRegistrarEmpleado.setAlignmentY(0.0F);

        pnlBordeNegro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblNombre.setText("Nombre");

        lblAppPaterno.setText("Apellido Paterno");

        lblApmMaterno.setText("Apellido Materno");

        lblUsuario.setText("Usuario");

        lblContraseña.setText("Contraseña");

        lblRepetirContraseña.setText("Repetir Contraseña");

        btnRegistrarE.setText("REGISTRAR");
        btnRegistrarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarEActionPerformed(evt);
            }
        });

        btnCancelarE.setText("CANCELAR");
        btnCancelarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBordeNegroLayout = new javax.swing.GroupLayout(pnlBordeNegro);
        pnlBordeNegro.setLayout(pnlBordeNegroLayout);
        pnlBordeNegroLayout.setHorizontalGroup(
            pnlBordeNegroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBordeNegroLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(pnlBordeNegroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAppPaterno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblApmMaterno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblRepetirContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancelarE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(60, 60, 60)
                .addGroup(pnlBordeNegroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegistrarE, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtnbEmpleado)
                    .addComponent(txtappEmpleado)
                    .addComponent(txtapmEmpleado)
                    .addComponent(txtusuario)
                    .addComponent(pwdEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                    .addComponent(pwdComparar))
                .addGap(70, 70, 70))
        );
        pnlBordeNegroLayout.setVerticalGroup(
            pnlBordeNegroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBordeNegroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBordeNegroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnbEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlBordeNegroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAppPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtappEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlBordeNegroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblApmMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtapmEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlBordeNegroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlBordeNegroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pwdEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlBordeNegroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pwdComparar)
                    .addComponent(lblRepetirContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlBordeNegroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCancelarE, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(btnRegistrarE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlBordeNegro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtRegistrarEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtRegistrarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlBordeNegro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // <editor-fold defaultstate="collapsed" desc="Btn Cancelar">
    private void btnCancelarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarEActionPerformed
        // TODO add your handling code here:
        Limpiar();
    }//GEN-LAST:event_btnCancelarEActionPerformed
    // </editor-fold>
    // <editor-fold defaultstate="collapsed" desc="Btn Registrar">
    private void btnRegistrarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarEActionPerformed
        // TODO add your handling code here:
        String nbEmpleado=TIPOS.clearEspacios(txtnbEmpleado.getText());
        String appEmpleado=TIPOS.clearEspacios(txtappEmpleado.getText());
        String apmEmpleado=TIPOS.clearEspacios(txtapmEmpleado.getText());
        String usuario=TIPOS.clearEspacios(txtusuario.getText());
        String pwsEmpleado;
        char psw[]=pwdEmpleado.getPassword();
        pwsEmpleado=new String(psw);
        String pwsComparar;
        char pswC[]=pwdComparar.getPassword();
        pwsComparar=new String(pswC);
        if(pwsEmpleado.equals(pwsComparar)){
            Empleado=new EMPLEADO();
            if(Empleado.RegistrarEmpleado(nbEmpleado,appEmpleado,
                    apmEmpleado,usuario,pwsEmpleado,idEmpleado)){
                idEmpleado=0;
                JOptionPane.showMessageDialog(this, "Guardado",
                    "Guardado", JOptionPane.INFORMATION_MESSAGE);

                pNLTablaEmpleados.deleteTabla();
                pNLTablaEmpleados.deletebtn();
                pNLTablaEmpleados.editbtn();
                Limpiar();
            }else{
                JOptionPane.showMessageDialog(this, "No se pudo guardar",
                    "Error al guardar", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Las contraseñas no concuerdan",
                    "Contraseña invalida", JOptionPane.ERROR_MESSAGE);
            pwdEmpleado.setText("");
            pwdComparar.setText("");
        }
    }//GEN-LAST:event_btnRegistrarEActionPerformed
    // </editor-fold>
    // <editor-fold defaultstate="collapsed" desc="Limpiar textbox">
    public static void Limpiar(){
        txtnbEmpleado.setText("");
        txtappEmpleado.setText("");
        txtapmEmpleado.setText("");
        txtusuario.setText("");
        pwdEmpleado.setText("");
        pwdComparar.setText("");
    }
    // </editor-fold>
    // <editor-fold defaultstate="collapsed" desc="Declaracion de variables">
    public static CAPA_NEGOCIOS.EMPLEADO Empleado;
    public static CAPA_PRESENTACION.ADMIN.PNLTablaEmpleados pNLTablaEmpleados=new PNLTablaEmpleados();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarE;
    private javax.swing.JButton btnRegistrarE;
    private javax.swing.JLabel lblApmMaterno;
    private javax.swing.JLabel lblAppPaterno;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRepetirContraseña;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel pnlBordeNegro;
    public static javax.swing.JPasswordField pwdComparar;
    public static javax.swing.JPasswordField pwdEmpleado;
    private javax.swing.JLabel txtRegistrarEmpleado;
    public static javax.swing.JTextField txtapmEmpleado;
    public static javax.swing.JTextField txtappEmpleado;
    public static javax.swing.JTextField txtnbEmpleado;
    public static javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
    // </editor-fold>
}
