/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CAPA_PRESENTACION.ADMIN;

import CAPA_NEGOCIOS.EMPLEADO;
import CAPA_PRESENTACION.HILOS.Reader;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static CAPA_PRESENTACION.ADMIN.PNLRegistrarEmpleado.txtnbEmpleado;
import static CAPA_PRESENTACION.ADMIN.PNLRegistrarEmpleado.txtappEmpleado;
import static CAPA_PRESENTACION.ADMIN.PNLRegistrarEmpleado.txtapmEmpleado;
import static CAPA_PRESENTACION.ADMIN.PNLRegistrarEmpleado.txtusuario;
import static CAPA_PRESENTACION.ADMIN.PNLRegistrarEmpleado.pwdEmpleado;
import static CAPA_PRESENTACION.ADMIN.PNLRegistrarEmpleado.pwdComparar;
import static CAPA_PRESENTACION.ADMIN.PNLRegistrarEmpleado.Limpiar;
/**
 *
 * @author Freak
 * @version Beta
 */
public final class PNLTablaEmpleados extends javax.swing.JPanel {

    /**
     * Creates new form PNLTablaEmpleados
     */
    // <editor-fold defaultstate="collapsed" desc="Constructor">
    public PNLTablaEmpleados() {
        modeloTabla=new DefaultTableModel(null,getColumnas()){
            @Override
            public boolean isCellEditable(int i, int i1) {
                return false;
            }
        };
        initComponents();
        Empleado.setFilasEmpleado(modeloTabla);
        //
        tblEmpleados.setDefaultRenderer(Object.class,new Reader());
        deletebtn();
        editbtn();
        for(int i=0;i<modeloTabla.getRowCount();i++){
            modeloTabla.setValueAt(btnEditar, i, 5);   
        }
        for(int i=0;i<modeloTabla.getRowCount();i++){
            modeloTabla.setValueAt(btnBorrar, i, 6);   
        }
        tblEmpleados.setRowHeight(30);
        
    }// </editor-fold>
    // <editor-fold defaultstate="collapsed" desc="Editor de Botnones">
    public void deletebtn(){
        iiD=new ImageIcon(getClass().getResource("/Imagenes/delete.png"));
        Image img= iiD.getImage();
        Image ximg= img.getScaledInstance(30, 30, (int) CENTER_ALIGNMENT);
        ImageIcon ico= new ImageIcon(ximg);
        btnBorrar.setIcon(ico);
    }   
    public void editbtn(){
        iiE=new ImageIcon(getClass().getResource("/Imagenes/Edit.png"));
        Image img= iiE.getImage();
        Image ximg= img.getScaledInstance(30, 30, (int) CENTER_ALIGNMENT);
        ImageIcon ico= new ImageIcon(ximg);
        btnEditar.setIcon(ico);
    }// </editor-fold>
    // <editor-fold defaultstate="collapsed" desc="Pinta Columnas de la tabla">
    private String[] getColumnas(){
        String columnas[]=new String[]{"Nombre","Apellido P","Apellido M","Usuario","Contraseña","Editar","Borrar"};
        return columnas;
    }// </editor-fold>
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmpleados = new javax.swing.JTable();
        txtTablaEmpleado = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(563, 329));

        tblEmpleados.setModel(modeloTabla);
        tblEmpleados.setColumnSelectionAllowed(true);
        tblEmpleados.setGridColor(new java.awt.Color(255, 255, 255));
        tblEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEmpleadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEmpleados);
        tblEmpleados.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        txtTablaEmpleado.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtTablaEmpleado.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtTablaEmpleado.setText("Empleados registrados");
        txtTablaEmpleado.setToolTipText("");
        txtTablaEmpleado.setAlignmentY(0.0F);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
                    .addComponent(txtTablaEmpleado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTablaEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // <editor-fold defaultstate="collapsed" desc="Accion botones tabla">
    private void tblEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEmpleadosMouseClicked
        // TODO add your handling code here:
        int colum=tblEmpleados.getColumnModel().getColumnIndexAtX(evt.getX());
        int row=evt.getY()/tblEmpleados.getRowHeight();
        
        if(row <modeloTabla.getRowCount() && row>=0 &&colum<modeloTabla.getColumnCount()&&colum>=5){
            Object value= modeloTabla.getValueAt(0, 6);
            if(value instanceof JButton){
                ((JButton)value).doClick();
                JButton btn=(JButton)value;
                if(colum==5){
                    int respuesta=JOptionPane.showConfirmDialog(null, "¿Deseas editar este usuario?");
                    if(JOptionPane.OK_OPTION==respuesta){
                        txtnbEmpleado.setText(modeloTabla.getValueAt(row, 0).toString());
                        txtappEmpleado.setText(modeloTabla.getValueAt(row, 1).toString());
                        txtapmEmpleado.setText(modeloTabla.getValueAt(row, 2).toString());
                        txtusuario.setText(modeloTabla.getValueAt(row, 3).toString());
                        pwdEmpleado.setText(modeloTabla.getValueAt(row, 4).toString());
                        pwdComparar.setText(modeloTabla.getValueAt(row, 4).toString());
                        idEmpleado=Empleado.isExistEmpleado(modeloTabla.getValueAt(row, 0).toString(),
                                modeloTabla.getValueAt(row, 1).toString(),
                                modeloTabla.getValueAt(row, 2).toString(),
                                modeloTabla.getValueAt(row, 3).toString(),
                                modeloTabla.getValueAt(row, 4).toString());
                    }
                }
                if(colum==6){
                    int respuesta=JOptionPane.showConfirmDialog(null, "¿Deseas eliminar este usuario?");
                    if(JOptionPane.OK_OPTION==respuesta){
                        nbEmpleado=modeloTabla.getValueAt(row, 0).toString();
                        appEmpleado=modeloTabla.getValueAt(row, 1).toString();
                        apmEmpleado=modeloTabla.getValueAt(row, 2).toString();
                        usuario=modeloTabla.getValueAt(row, 3).toString();
                        pwsEmpleado=modeloTabla.getValueAt(row, 4).toString();
                        if(Empleado.DeleteEmpleado(nbEmpleado,appEmpleado,apmEmpleado,usuario,pwsEmpleado)){
                            JOptionPane.showMessageDialog(this, "Empleado eliminado",
                                "Eliminado", JOptionPane.INFORMATION_MESSAGE);
                            deleteTabla();
                            Limpiar();
                        }else{
                            JOptionPane.showMessageDialog(this, "Error al eliminar empleado",
                                "Error al guardar", JOptionPane.ERROR_MESSAGE);
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_tblEmpleadosMouseClicked
    // </editor-fold>
    // <editor-fold defaultstate="collapsed" desc="Actualiza tabla">
    public void deleteTabla(){
        btnEditar=new JButton();
        btnBorrar=new JButton();
        Empleado.setFilasEmpleado(modeloTabla);
        btnBorrar.setName("Delete");
        btnEditar.setName("Editar");
        for(int i=0;i<modeloTabla.getRowCount();i++){
            modeloTabla.setValueAt(btnEditar, i, 5);   
        }
        for(int i=0;i<modeloTabla.getRowCount();i++){
            modeloTabla.setValueAt(btnBorrar, i, 6);   
        }
        deletebtn();
        editbtn();
    }// </editor-fold>
    // <editor-fold defaultstate="collapsed" desc="Declaracion de variables">
    public static DefaultTableModel modeloTabla;
    public static JButton btnEditar=new JButton();
    public static JButton btnBorrar=new JButton();
    public ImageIcon iiD,iiE;
    private static String nbEmpleado,appEmpleado,apmEmpleado,usuario,pwsEmpleado;
    public static int idEmpleado;
    private static final CAPA_NEGOCIOS.EMPLEADO Empleado=new EMPLEADO();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEmpleados;
    private javax.swing.JLabel txtTablaEmpleado;
    // End of variables declaration//GEN-END:variables
    // </editor-fold>
}
